#pragma once

#include <juce_core/juce_core.h>
#include "../AutosamplerState.h"
#include "WavWriter.h"
#include <map>

class SFZExporter
{
public:
    static bool exportSamples(const std::map<int, SampleData>& samples,
                              const juce::String& packName,
                              const juce::File& outputDirectory)
    {
        if (samples.empty())
            return false;

        // Create output directory if needed
        if (!outputDirectory.exists())
            outputDirectory.createDirectory();

        // Write WAV files
        for (auto& [midiNote, data] : samples)
        {
            auto wavFilename = WavWriter::getWavFilename(packName, midiNote);
            auto wavFile = outputDirectory.getChildFile(wavFilename);

            if (!WavWriter::writeWavFile(wavFile, data))
                return false;
        }

        // Generate and write SFZ file
        auto sfzFile = outputDirectory.getChildFile(packName + ".sfz");
        auto sfzContent = generateSFZContent(samples, packName);
        return sfzFile.replaceWithText(sfzContent);
    }

private:
    static juce::String generateSFZContent(const std::map<int, SampleData>& samples,
                                            const juce::String& packName)
    {
        juce::String content;
        content += "// " + packName + " - Generated by JUCE Autosampler\n\n";
        content += "<global>\n";
        content += "lovel=0\n";
        content += "hivel=127\n\n";

        auto it = samples.begin();
        while (it != samples.end())
        {
            int midiNote = it->first;
            auto wavFilename = WavWriter::getWavFilename(packName, midiNote);

            // Calculate lokey/hikey: midpoint between adjacent sampled notes
            int lokey = midiNote;
            int hikey = midiNote;

            if (it != samples.begin())
            {
                auto prev = std::prev(it);
                lokey = prev->first + (midiNote - prev->first) / 2 + 1;
            }
            else
            {
                lokey = midiNote;
            }

            auto next = std::next(it);
            if (next != samples.end())
            {
                hikey = midiNote + (next->first - midiNote) / 2;
            }
            else
            {
                hikey = midiNote;
            }

            content += "<region>\n";
            content += "sample=" + wavFilename + "\n";
            content += "lokey=" + juce::String(lokey) + "\n";
            content += "hikey=" + juce::String(hikey) + "\n";
            content += "pitch_keycenter=" + juce::String(midiNote) + "\n";
            content += "\n";

            ++it;
        }

        return content;
    }
};
